export const CIUDADES_COLOMBIA = [
  // Sucre (prioritarias por ubicación de la IPS)
  "Sincelejo",
  "Corozal",
  "San Marcos",
  "Sampués",
  "Morroa",
  "Santiago de Tolú",
  "Coveñas",
  "San Onofre",
  "Ovejas",
  "Los Palmitos",
  "Majagual",
  "Guaranda",
  "Sucre",
  "Galeras",
  "Sincé",
  "Buenavista",
  "La Unión",
  "Palmito",
  "San Pedro",
  "Chalán",
  "Coloso",
  "El Roble",
  "San Benito Abad",
  "Tolú Viejo",
  // Bolívar
  "Cartagena",
  "Magangué",
  "El Carmen de Bolívar",
  "Mompós",
  "Turbaco",
  "Arjona",
  "Magangu",
  "Villanueva",
  "San Juan Nepomuceno",
  "Simití",
  "Achí",
  "Cantagallo",
  "Cicuco",
  "Clemencia",
  "Córdoba",
  "El Guamo",
  "El Peñón",
  "Hatillo de Loba",
  "Margarita",
  "Montecristo",
  "Morales",
  "Norosí",
  "Pinillos",
  "Regidor",
  "Río Viejo",
  "San Cristóbal",
  "San Estanislao",
  "San Jacinto",
  "San Jacinto del Cauca",
  "San Martín de Loba",
  "San Pablo",
  "Santa Catalina",
  "Santa Rosa",
  "Santa Rosa del Sur",
  "Soplaviento",
  "Talaigua Nuevo",
  "Tiquisio",
  "Zambrano",
  // Córdoba
  "Montería",
  "Lorica",
  "Sahagún",
  "Montelíbano",
  "Cereté",
  "Planeta Rica",
  "Tierralta",
  "Ayapel",
  "Chinú",
  "Ciénaga de Oro",
  "Cotorra",
  "La Apartada",
  "Momil",
  "Moñitos",
  "Pueblo Nuevo",
  "Puerto Escondido",
  "Puerto Libertador",
  "Purísima",
  "San Andrés de Sotavento",
  "San Antero",
  "San Bernardo del Viento",
  "San Carlos",
  "San José de Uré",
  "San Pelayo",
  "Tuchín",
  "Valencia",
  // Atlántico
  "Barranquilla",
  "Soledad",
  "Malambo",
  "Sabanalarga",
  "Baranoa",
  "Puerto Colombia",
  "Galapa",
  "Santo Tomás",
  "Palmar de Varela",
  "Polonuevo",
  "Ponedera",
  "Repelón",
  "Sabanagrande",
  "Santa Lucía",
  "Suan",
  "Tubará",
  "Usiacurí",
  // Bogotá D.C.
  "Bogotá",
  // Antioquia
  "Medellín",
  "Bello",
  "Itagüí",
  "Envigado",
  "Apartadó",
  "Turbo",
  "Rionegro",
  "Caucasia",
  "Sabaneta",
  "La Estrella",
  "Copacabana",
  "Girardota",
  "Barbosa",
  "Caldas",
  "Chigorodó",
  "Carepa",
  "Necoclí",
  // Valle del Cauca
  "Cali",
  "Buenaventura",
  "Palmira",
  "Buga",
  "Tuluá",
  "Cartago",
  "Yumbo",
  "Jamundí",
  "Candelaria",
  "Florida",
  "Pradera",
  "Roldanillo",
  "Sevilla",
  "Zarzal",
  // Cundinamarca
  "Soacha",
  "Fusagasugá",
  "Facatativá",
  "Zipaquirá",
  "Chía",
  "Mosquera",
  "Madrid",
  "Cajicá",
  "Girardot",
  "La Mesa",
  "Funza",
  "Tocancipá",
  "Sibaté",
  "Cota",
  "Sopó",
  "Tabio",
  "Tenjo",
  "Villeta",
  // Santander
  "Bucaramanga",
  "Floridablanca",
  "Girón",
  "Piedecuesta",
  "Barrancabermeja",
  "San Gil",
  "Socorro",
  "Málaga",
  "Lebrija",
  "Vélez",
  // Norte de Santander
  "Cúcuta",
  "Ocaña",
  "Pamplona",
  "Villa del Rosario",
  "Los Patios",
  "El Zulia",
  "Tibú",
  // Boyacá
  "Tunja",
  "Duitama",
  "Sogamoso",
  "Chiquinquirá",
  "Paipa",
  "Moniquirá",
  "Puerto Boyacá",
  "Muzo",
  // Tolima
  "Ibagué",
  "Espinal",
  "Melgar",
  "Honda",
  "Chaparral",
  "Líbano",
  "Mariquita",
  // Huila
  "Neiva",
  "Pitalito",
  "Garzón",
  "La Plata",
  "Campoalegre",
  // Nariño
  "Pasto",
  "Tumaco",
  "Ipiales",
  "Túquerres",
  "La Unión",
  // Caldas
  "Manizales",
  "La Dorada",
  "Riosucio",
  "Chinchiná",
  "Villamaría",
  // Risaralda
  "Pereira",
  "Dosquebradas",
  "Santa Rosa de Cabal",
  "La Virginia",
  "Marsella",
  // Quindío
  "Armenia",
  "Calarcá",
  "Montenegro",
  "Quimbaya",
  // Meta
  "Villavicencio",
  "Acacías",
  "Granada",
  "San Martín",
  "Restrepo",
  // Cauca
  "Popayán",
  "Santander de Quilichao",
  "Patía",
  "Puerto Tejada",
  // Cesar
  "Valledupar",
  "Aguachica",
  "Bosconia",
  "Codazzi",
  "La Jagua de Ibirico",
  // La Guajira
  "Riohacha",
  "Maicao",
  "Uribia",
  "Manaure",
  "Fonseca",
  // Magdalena
  "Santa Marta",
  "Ciénaga",
  "Fundación",
  "Plato",
  "El Banco",
  // Casanare
  "Yopal",
  "Aguazul",
  "Villanueva",
  "Tauramena",
  // Arauca
  "Arauca",
  "Saravena",
  "Tame",
  // Putumayo
  "Mocoa",
  "Puerto Asís",
  "Orito",
  // Caquetá
  "Florencia",
  "San Vicente del Caguán",
  // Chocó
  "Quibdó",
  "Istmina",
  "Tumaco",
  // San Andrés
  "San Andrés",
  "Providencia",
  // Amazonas
  "Leticia",
  // Vaupés
  "Mitú",
  // Guainía
  "Inírida",
  // Vichada
  "Puerto Carreño",
  // Guaviare
  "San José del Guaviare",
].sort((a, b) => a.localeCompare(b, "es"));
